fr_dict = [
    "Quitter",
    "Cacher",
    "Nouvelle partie",
    "JOUER",
    "Envahir",
    "Au tour de {}",
    "Bravo à tous, bel effort.",
    "Tuto : OFF",
    "Tuto : ON",
    "État du réseau :",
    "Connecté",
    "Déconnecté",
    "Langue :",
    "Paramètres",
    "< Retour",
    "Étape suivante",
    "CONSTRUCTION",
    "ATTAQUE",
    "REORGANISATION",
    "Rapatrier",
    "Déplacer",
    "Sélectionner",
    "Passer",
    "{} a gagné !",
    "OK",
    "Nombre de joueurs",
    "Choisis ton drapeau",
    "Combien de joueurs participeront à cette partie ?",
    "Choisis un peuple, cette étape est facile !",
    "Choisis cette région ou passe ton tour !\nTu as droit à 3 tirages.",
    "Clique sur un pays pour y planter ton drapeau !\nPendant la partie, tu devras le protéger à tous prix !",
    "Construis des bâtiments !\nIls coûtent 3 lingots chacun.\nLes mines rapportent 4 lingots par tour, et les camps, 3 soldats par tour !",
    "C'est le moment d'étendre ton empire !\nPrends des soldats avec le clic droit de ta souris, puis envahis tes voisins !",
    "Avant de finir ton tour, réorganise tes troupes !\nTes adversaires pourraient attaquer ton empire !",
    "Aucune connection internet",
    "{}",
    "Un jour\npeut-être ?",
    "Certaines traductions pourraient ne pas fonctionner",
    "Salut !\nMoi c'est Pony la chouette !\nOn me paie pour que je te fasse le tuto !",
    "Jaune",
    "Bleu",
    "Vert",
    "Violet",
    "Gris",
    "Rouge",
]